aliases:
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v1-yarn-{{ .Branch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &yarn
    name: Yarn Install
    command: yarn install --non-interactive --cache-folder ~/.cache/yarn

defaults: &defaults
  docker:
    - image: circleci/node:10

  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults

    working_directory: ~/repo

    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - run:
          name: Test
          command: yarn test --maxWorkers=1

  deployment:
    <<: *defaults

    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - run:
          name: Test
          command: yarn test --maxWorkers=1
      - run: NODE_ENV=production yarn build && chmod +x deploy.sh && ~/repo/deploy.sh "mattlo.io"

workflows:
  version: 2
  chipbot-workflows:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - deployment:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
